namespace SportBettingScraper.Core;

public static class SkySportsLeagues
{
    public static List<League> GetLeagues()
    {
        return
        [
            new League("Premier League",
                   "https://www.skysports.com/premier-league-table",
                   "https://www.skysports.com/premier-league-fixtures"),
            new League("Bundesliga",
                   "https://www.skysports.com/bundesliga-table",
                   "https://www.skysports.com/bundesliga-scores-fixtures"),
            new League("La Liga",
                   "https://www.skysports.com/la-liga-table",
                   "https://www.skysports.com/la-liga-scores-fixtures"),
            new League("Serie A",
                   "https://www.skysports.com/serie-a-table",
                   "https://www.skysports.com/serie-a-scores-fixtures"),
            new League("Ligue 1",
                   "https://www.skysports.com/ligue-1-table",
                   "https://www.skysports.com/ligue-1-scores-fixtures"),
            new League("Bundesliga Women",
                   "https://www.skysports.com/german-bundesliga-women-table",
                   "https://www.skysports.com/german-bundesliga-women-scores-fixtures"),
            new League("Laliga Women",
                   "https://www.skysports.com/womens-spanish-primera-division-table",
                   "https://www.skysports.com/womens-spanish-primera-division-scores-fixtures"),
            new League("Ligue 1 Women",
                   "https://www.skysports.com/womens-french-division-1-table",
                   "https://www.skysports.com/womens-french-division-1-scores-fixtures"),
            new League("Australian A-League",
                   "https://www.skysports.com/football/competitions/australian-a-league/table",
                   "https://www.skysports.com/australian-a-league-scores-fixtures"),
            new League("Austrian Bundesliga",
                   "https://www.skysports.com/football/competitions/austrian-t-mobile-bundesliga/table",
                   "https://www.skysports.com/austrian-t-mobile-bundesliga-scores-fixtures"),
            new League("Belgian First Division A",
                   "https://www.skysports.com/jupiler-league-table",
                   "https://www.skysports.com/jupiler-league-scores-fixtures"),
            new League("Chinese Super League",
                   "https://www.skysports.com/chinese-super-league-table",
                   "https://www.skysports.com/chinese-super-league-scores-fixtures"),
            new League("Danish Superligaen",
                   "https://www.skysports.com/football/competitions/danish-superligaen/table",
                   "https://www.skysports.com/danish-superligaen-scores-fixtures"),
            new League("Finnish Veikkausliga",
                   "https://www.skysports.com/football/competitions/finnish-veikkausliga/table",
                   "https://www.skysports.com/finnish-veikkausliga-scores-fixtures"),
            new League("Bundesliga 2",
                   "https://www.skysports.com/football/competitions/german-2-bundesliga/table",
                   "https://www.skysports.com/german-2-bundesliga-scores-fixtures"),
            new League("Bundesliga 3",
                   "https://www.skysports.com/football/competitions/german-3-liga/table",
                   "https://www.skysports.com/german-3-liga-scores-fixtures"),
            new League("Greek Super League",
                   "https://www.skysports.com/football/competitions/greek-super-league/table",
                   "https://www.skysports.com/greek-super-league-scores-fixtures"),
            new League("Dutch Eredivisie",
                   "https://www.skysports.com/eredivisie-table",
                   "https://www.skysports.com/eredivisie-scores-fixtures"),
            new League("Hungarian NB1",
                   "https://www.skysports.com/football/competitions/hungarian-nb1/table",
                   "https://www.skysports.com/hungarian-nb1-scores-fixtures"),
            new League("Serie B",
                   "https://www.skysports.com/football/competitions/italian-serie-b/table",
                   "https://www.skysports.com/italian-serie-b-scores-fixtures"),
            new League("Japanese J League",
                   "https://www.skysports.com/football/competitions/japanese-j-league/table",
                   "https://www.skysports.com/japanese-j-league-scores-fixtures"),
            new League("Norwegian Eliteserien",
                   "https://www.skysports.com/football/competitions/norwegian-eliteserien/table",
                   "https://www.skysports.com/norwegian-eliteserien-scores-fixtures"),
            new League("Polish Ekstraklasa",
                   "https://www.skysports.com/football/competitions/polish-ekstraklasa/table",
                   "https://www.skysports.com/polish-ekstraklasa-scores-fixtures"),
            new League("Portuguese Primeira Liga",
                   "https://www.skysports.com/portuguese-liga-table",
                   "https://www.skysports.com/portuguese-liga-scores-fixtures"),
            new League("Russia - Premier Liga",
                   "https://www.skysports.com/football/competitions/russia-premier-liga/table",
                   "https://www.skysports.com/russia-premier-liga-scores-fixtures"),
            new League("Swedish Allsvenskan",
                   "https://www.skysports.com/football/competitions/swedish-allsvenskan/table",
                   "https://www.skysports.com/swedish-allsvenskan-scores-fixtures"),
            new League("Swiss Super League",
                   "https://www.skysports.com/football/competitions/swiss-super-league/table",
                   "https://www.skysports.com/swiss-super-league-scores-fixtures"),
            new League("Turkish Super Lig",
                   "https://www.skysports.com/football/competitions/turkish-super-lig/table",
                   "https://www.skysports.com/turkish-super-lig-scores-fixtures"),
            new League("Barclays Women's Super League",
                   "https://www.skysports.com/womens-super-league-table",
                   "https://www.skysports.com/womens-super-league-scores-fixtures"),
            new League("Sky Bet Championship",
                   "https://www.skysports.com/championship-table",
                   "https://www.skysports.com/championship-scores-fixtures"),
            new League("Sky Bet League One",
                   "https://www.skysports.com/league-1-table",
                   "https://www.skysports.com/league-1-scores-fixtures"),
            new League("Scottish Premiership",
                   "https://www.skysports.com/scottish-premier-table",
                   "https://www.skysports.com/scottish-premier-scores-fixtures"),
            new League("Scottish Women's Premier League",
                   "https://www.skysports.com/womens-scottish-premier-league-table",
                   "https://www.skysports.com/womens-scottish-premier-league-scores-fixtures"),
            new League("Scottish Championship",
                   "https://www.skysports.com/scottish-championship-table",
                   "https://www.skysports.com/scottish-championship-scores-fixtures"),
            new League("Welsh Premier League",
                   "https://www.skysports.com/welsh-premier-league-table",
                   "https://www.skysports.com/welsh-premier-league-scores-fixtures"),
            new League("Ireland Premier Division",
                   "https://www.skysports.com/football/competitions/league-of-ireland-premier-division/table",
                   "https://www.skysports.com/league-of-ireland-premier-division-scores-fixtures"),
        ];
    }
}
